import sys, socket, time, struct, threading, requests

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")

print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("ur mom gae")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
print ("lol get fukt ghost a big boat loader")
